name: Build Ubuntu Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures all history and tags are fetched
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-make

    - name: Build project
      run: |
         cd source
         make

    - name: Run tests
      run: |
        cd source
        make test
    - name: Prepare package files
      run: |
        # Try to get the latest tag, use a default if none exists
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
        
        # If no tag was found, use the short commit hash
        if [ "$LATEST_TAG" = "v0.1.0" ]; then
          LATEST_TAG=$(git rev-parse --short HEAD)
        fi

        cd source
        mkdir -p debian
        cat << EOF > debian/control
        Source: json-graylog-tcp-logger
        Section: utils
        Priority: optional
        Maintainer: Darek <darek.margas@gmail.com>
        Build-Depends: debhelper (>= 9)
        Standards-Version: 3.9.8

        Package: json-graylog-tcp-logger
        Architecture: any
        Depends: \${shlibs:Depends}, \${misc:Depends}
        Description: STDIN to TCP Graylog logger
         This is Graylog TCP logger written in C
         This process takes STDIN as input, assuming one message per line, terminated by 0x0a. 
         Then, replaces termination with 0x00 to comply with Graylog TCP format and sends it to one of (up to) two Graylog servers. 
        EOF

        echo "11" > debian/compat
        
        cat << EOF > debian/rules
        #!/usr/bin/make -f
        %:
        	dh \$@
        EOF
        chmod +x debian/rules

        cat << EOF > debian/changelog
        json-graylog-tcp-logger ($LATEST_TAG) unstable; urgency=medium

          * Release $LATEST_TAG

         -- Darek <darek.margas@gmail.com>  $(date -R)
        EOF

        # Verify files were created
        #ls -R debian

    - name: Build Debian package
      run: |
        cd source
        dpkg-buildpackage -us -uc -b

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-package
        path: ./*.deb
        if-no-files-found: error
