name: GELFsender test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: | 
        cd source
        make
    - name: make test
      run: |
        cd source
        make test
